name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/5 * * * *" 
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 625b13c2df171d2ddb9e71b1d5675621
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
